### ISSUE TITLE
Error on building the development branch

### ISSUE THREAD

**Issue by Phavion** [svsticky/static-sticky#74]
Apparently, the react-slideshow-image package creates an error on 'npm run build'. According to the message, the error is situated in an automatically generated .js file (render-page.js) in /public which I can't find back. Even with hidden files viewing on.

**Comment by Phavion** [comment]
```/home/niels/github/static-sticky/public/render-page.js:6189
          requestAnimationFrame(animate);
          ^

ReferenceError: requestAnimationFrame is not defined
    at animate (/home/niels/github/static-sticky/public/render-page.js:6189:11)
    at Slideshow.slideImages (/home/niels/github/static-sticky/public/render-page.js:6193:9)
    at Slideshow.preSlide (/home/niels/github/static-sticky/public/render-page.js:6067:12)
    at Timeout.<anonymous> (/home/niels/github/static-sticky/public/render-page.js:6090:25)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)```

**Comment by Riscky** [comment]
This is a very old issue which I could not reproduce
